name: Send cliq
on:
  workflow_call:
    inputs:
      texto:
        type: string
        required: false
jobs:
  send:
    runs-on: ubuntu-latest
    steps:

      - name: Set repository name
        run: echo ${{ inputs.texto }}